# Workflow for running Meticulous app against an existing preview URL

name: Meticulous

# Important: The workflow needs to run both on pushes to your main branch and on pull requests.
# It needs to run on your main branch because it'll use the results from the
# base commit of the PR on the main branch to compare against.
on:
  push:
    branches:
      - main
  pull_request: {}
  # Important: We need the workflow to be triggered on workflow_dispatch events,
  # so that Meticulous can run the workflow on the base commit to compare
  # against if an existing workflow hasn't run
  workflow_dispatch: {}

# Important: The workflow needs all the permissions below.
# These permissions are mainly need to post and update the status check and
# feedback comment on your PR. Meticulous wonâ€™t work without them.
permissions:
  actions: write
  checks: write
  contents: read
  discussions: write
  pull-requests: write
  statuses: write
  deployments: read

jobs:
  test:
    name: Report diffs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          use-deployment-url: true
          allowed-environments: |
            production-preview
            production

